import React, { useState, useRef, useEffect } from "react";
import {
  Upload,
  Camera,
  FileText,
  Volume2,
  Share2,
  AlertTriangle,
  AlertOctagon,
  CheckCircle2,
  Check,
  ArrowLeft,
  Type,
  Home as HomeIcon,
  HeartHandshake,
  ShieldCheck,
  Lock,
  X,
  Square,
  PhoneCall,
  RotateCcw,
  HelpCircle,
  Receipt,
  Wifi,
  CalendarCheck,
  Clock,
  CalendarX,
  Info,
  ExternalLink,
  ListChecks,
  ChevronRight,
  Circle,
} from "lucide-react";

const FONTS = `
@import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap');
`;

const TOKENS = {
  ink: "#16326B",
  inkSoft: "#2C5AA8",
  paper: "#F7F5EF",
  paperDark: "#E4E7EE",
  brick: "#B23A2E",
  forest: "#2C5AA8",
  text: "#20242E",
  textMuted: "#5B6474",
};

const STEPS = ["Subir", "Confirmar", "Revisar", "Listo"];

function speak(text, { onStart, onEnd } = {}) {
  if (!("speechSynthesis" in window)) {
    if (onEnd) onEnd();
    return;
  }
  window.speechSynthesis.cancel();
  const utter = new SpeechSynthesisUtterance(text);
  utter.lang = "es-MX";
  utter.rate = 0.95;
  utter.pitch = 1;
  const voices = window.speechSynthesis.getVoices();
  const esVoice = voices.find((v) => v.lang && v.lang.toLowerCase().startsWith("es"));
  if (esVoice) utter.voice = esVoice;
  utter.onstart = () => onStart && onStart();
  utter.onend = () => onEnd && onEnd();
  utter.onerror = () => onEnd && onEnd();
  window.speechSynthesis.speak(utter);
}

function stopSpeaking() {
  if ("speechSynthesis" in window) window.speechSynthesis.cancel();
}

function buildSpokenSummary(result, confianzaTexto) {
  const campos = result.campos.map((c) => `${c.label}: ${c.value}.`).join(" ");
  return `${result.tipo}. ${confianzaTexto}. ${campos} Ojo con esto: ${result.alerta} Lo esencial: ${result.esencial.join(". ")}.`;
}

const HOME_EXPLANATION =
  "Kalan te ayuda a entender tus contratos y documentos. Sube un P D F o toma una foto, confirma que es el documento correcto, espera unos segundos mientras lo analizamos, y te mostramos un resumen fácil de entender con lo más importante.";

// A short, fictional contract used for the "usar contrato de ejemplo" demo path,
// so the real AI pipeline has something real to analyze without needing a file.
const SAMPLE_CONTRACT_TEXT = `CONTRATO DE PRESTACIÓN DE SERVICIOS DE TELEFONÍA MÓVIL

Entre TeleConecta S.A. de C.V. ("la Empresa") y el Cliente que firma abajo.

1. PLAN CONTRATADO: Plan Ilimitado Plus, con costo mensual de $399 MXN, facturado el día 10 de cada mes.
2. VIGENCIA: El presente contrato tiene una duración forzosa de 18 meses a partir de la fecha de firma.
3. EQUIPO: Se entrega un equipo telefónico en comodato, valuado en $8,500 MXN.
4. CANCELACIÓN ANTICIPADA: En caso de que el Cliente cancele el servicio antes de cumplir los 18 meses de vigencia forzosa, deberá cubrir una penalización equivalente al 80% de las mensualidades restantes, además de pagar el valor total del equipo si no es devuelto en buen estado.
5. INCREMENTOS: La Empresa podrá ajustar la tarifa mensual una vez al año conforme a la inflación, notificando al Cliente con 30 días de anticipación.
6. SOPORTE: El Cliente tiene derecho a soporte técnico telefónico sin costo adicional.
7. DATOS: El Cliente autoriza el uso de sus datos de consumo para fines de facturación y mejora del servicio.

Firmado por ambas partes.`;

// A short, fictional ID description used for the "usar identificación de ejemplo" demo path.
const SAMPLE_ID_TEXT = `IDENTIFICACIÓN OFICIAL PARA VOTAR - INSTITUTO NACIONAL ELECTORAL
Nombre: MARÍA EJEMPLO GONZÁLEZ
CURP: EJEM580305MDFXXX00
Fecha de nacimiento: 05/03/1958
Domicilio: Calle Ejemplo 123, Ciudad de México
Sección: 1234
VIGENCIA 2019 2027`;

// Curated, hand-written step-by-step guides for online trámites.
// Deliberately NOT generated by the AI: government steps must stay accurate,
// so this content should be written/verified by the team and updated when a portal changes.
const TRAMITES = [
  {
    id: "curp",
    titulo: "Obtener o reimprimir tu CURP",
    descripcion: "Consigue el documento oficial de tu CURP en minutos, sin ir a ninguna oficina.",
    disponible: true,
    sitioOficial: "https://www.gob.mx/curp/",
    documentos: ["No necesitas ningún documento a la mano, solo tus datos personales."],
    pasos: [
      { titulo: "Entra al sitio oficial", detalle: "Ve a gob.mx/curp desde tu celular o computadora. Es un sitio del gobierno y es gratuito." },
      { titulo: "Elige buscar tu CURP", detalle: "Si ya conoces tu CURP, escríbela directamente. Si no la recuerdas, elige la opción de buscar con tus datos personales." },
      { titulo: "Escribe tus datos personales", detalle: "Tu nombre completo, fecha de nacimiento, sexo y el estado donde naciste, tal como aparecen en tu acta de nacimiento." },
      { titulo: "Da clic en \"Buscar\"", detalle: "El sistema revisa tus datos y te muestra tu CURP si todo coincide correctamente." },
      { titulo: "Descarga el documento", detalle: "Aparecerá un botón para descargar un PDF. Ese PDF ya es válido, no necesita sello ni firma adicional." },
      { titulo: "Guárdalo o imprímelo", detalle: "Guárdalo en tu celular o imprímelo. Ya puedes usarlo para el trámite que te lo pidió." },
    ],
  },
  {
    id: "sat",
    titulo: "Constancia de situación fiscal (SAT)",
    descripcion: "Descarga el documento oficial que muchos trámites y trabajos te piden, sin ir a las oficinas del SAT.",
    disponible: true,
    sitioOficial: "https://www.sat.gob.mx/personas",
    documentos: [
      "Tu RFC (Registro Federal de Contribuyentes).",
      "Tu Contraseña del SAT (también llamada CIEC) o tu e.firma. Si no la tienes, el mismo sitio te permite generarla con tu CURP.",
    ],
    pasos: [
      { titulo: "Entra al sitio oficial del SAT", detalle: "Ve a sat.gob.mx y busca la sección para personas físicas." },
      { titulo: "Busca \"Constancia de situación fiscal\"", detalle: "Está dentro de los trámites más usados; también puedes escribirlo en el buscador del sitio." },
      { titulo: "Inicia sesión", detalle: "Usa tu RFC y tu Contraseña del SAT. Si nunca la has creado, el sitio tiene una opción para generarla usando tu CURP." },
      { titulo: "Genera la constancia", detalle: "Dentro del trámite, elige la opción para generar la Constancia de Situación Fiscal con Cédula de Identificación Fiscal (CIF)." },
      { titulo: "Descarga el PDF", detalle: "El documento se descarga al instante y ya es válido para entregarlo donde te lo pidan; incluye un código QR para verificarlo." },
      { titulo: "Guárdalo o imprímelo", detalle: "Guárdalo en tu celular o imprímelo. Muchos trabajos y trámites lo piden con menos de un mes de haber sido generado." },
    ],
  },
  {
    id: "imss",
    titulo: "Consultar tu vigencia de derechos (IMSS)",
    descripcion: "Revisa si tienes derecho vigente a servicio médico del IMSS en este momento, sin ir a la clínica.",
    disponible: true,
    sitioOficial: "https://www.imss.gob.mx/",
    documentos: ["Tu CURP a la mano."],
    pasos: [
      { titulo: "Entra al sitio oficial del IMSS", detalle: "Ve a imss.gob.mx y busca la sección de \"IMSS digital\" o servicios en línea." },
      { titulo: "Busca \"Vigencia de derechos\"", detalle: "Es una consulta gratuita que te dice si en este momento tienes derecho a servicio médico." },
      { titulo: "Escribe tu CURP", detalle: "Escríbela tal como aparece en tu identificación, sin espacios." },
      { titulo: "Resuelve la verificación de seguridad", detalle: "Es un código o casillas para confirmar que no eres un robot; solo síguelo." },
      { titulo: "Da clic en consultar", detalle: "El sistema te mostrará si tu vigencia está activa y hasta qué fecha." },
      { titulo: "Revisa el resultado", detalle: "Si no tienes vigencia y crees que deberías, es momento de contactar a tu patrón (si trabajas) o acudir a tu clínica asignada." },
    ],
  },
];
// Kept static (not AI-generated) so we never show a fabricated or wrong URL.
const OFFICIAL_LINKS = {
  INE: "https://www.ine.mx",
  Pasaporte: "https://www.gob.mx/sre/acciones-y-programas/pasaportes",
  CURP: "https://www.gob.mx/curp/",
};

function findOfficialLink(documento) {
  if (!documento) return null;
  const key = Object.keys(OFFICIAL_LINKS).find((k) => documento.toLowerCase().includes(k.toLowerCase()));
  return key ? { label: key, url: OFFICIAL_LINKS[key] } : null;
}

function buildSpokenVigencia(result) {
  const estadoTexto = {
    vigente: "Está vigente.",
    por_vencer: "Está a punto de vencer.",
    vencido: "Ya está vencido.",
    sin_fecha: "Este documento no tiene fecha de vencimiento.",
  }[result.estado] || "";
  return `${result.documento}. ${estadoTexto} ${result.mensaje} ${result.recomendacion || ""}`;
}

function buildVigenciaInstructions() {
  const hoy = new Date().toLocaleDateString("es-MX", { year: "numeric", month: "long", day: "numeric" });
  return `Eres un asistente que ayuda a cualquier persona a saber si un documento oficial de identificación sigue vigente.
Hoy es ${hoy}.
Analiza el documento adjunto (una identificación oficial, como INE, pasaporte, licencia de conducir, u otro) y responde ÚNICAMENTE con un objeto JSON válido, sin texto antes ni después, sin marcadores de código, con esta forma EXACTA:

{
  "documento": "nombre corto del documento detectado, ej. 'INE', 'Pasaporte', 'Licencia de conducir'",
  "tiene_vencimiento": true o false,
  "fecha_vencimiento": "la fecha tal como aparece o se pueda calcular, o null si no aplica",
  "estado": "vigente" | "por_vencer" | "vencido" | "sin_fecha",
  "dias": número de días restantes (positivo) o días desde que venció (positivo), o null si no aplica,
  "mensaje": "una sola oración clara explicando la situación, en lenguaje simple",
  "recomendacion": "una sola oración con el siguiente paso a seguir; si está vigente y falta mucho tiempo, una nota tranquilizadora"
}

Usa "por_vencer" si vence en menos de 90 días. Usa "sin_fecha" solo si el tipo de documento genuinamente no tiene vencimiento (como una CURP o un acta de nacimiento).
No uses tecnicismos. No agregues texto fuera del JSON. No uses comillas triples ni la palabra json antes del objeto.`;
}

async function analyzeVigencia({ file, useSample }) {
  const contentBlocks = [];

  if (useSample || !file) {
    contentBlocks.push({ type: "text", text: "Documento a analizar:\n\n" + SAMPLE_ID_TEXT });
  } else if (file.type === "application/pdf") {
    const base64 = await fileToBase64(file);
    contentBlocks.push({ type: "document", source: { type: "base64", media_type: "application/pdf", data: base64 } });
  } else if (file.type && file.type.startsWith("image/")) {
    const base64 = await fileToBase64(file);
    contentBlocks.push({ type: "image", source: { type: "base64", media_type: file.type, data: base64 } });
  } else {
    throw new Error("Ese tipo de archivo no lo podemos leer.");
  }

  contentBlocks.push({ type: "text", text: buildVigenciaInstructions() });

  const response = await fetchWithRetry({
    model: "claude-sonnet-4-6",
    max_tokens: 600,
    messages: [{ role: "user", content: contentBlocks }],
  });

  const data = await response.json();
  const textBlock = (data.content || []).find((b) => b.type === "text");
  if (!textBlock || !textBlock.text) {
    throw new Error("El analizador no devolvió una respuesta.");
  }

  const cleaned = textBlock.text.replace(/```json|```/g, "").trim();
  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch (e) {
    throw new Error("No entendimos el resultado del análisis.");
  }

  if (!parsed.documento || !parsed.estado) {
    throw new Error("El resultado no tiene el formato esperado.");
  }
  return parsed;
}

const ANALYSIS_INSTRUCTIONS = `Eres un asistente que ayuda a cualquier persona, sin conocimientos legales, a entender contratos y documentos.
Analiza el documento adjunto y responde ÚNICAMENTE con un objeto JSON válido, sin texto antes ni después, sin marcadores de código, con esta forma EXACTA:

{
  "tipo": "nombre corto y claro del tipo de contrato en español, ej. 'Contrato de Arrendamiento'",
  "confianza": "alta" | "media" | "baja",
  "campos": [
    { "label": "nombre corto del dato (2-3 palabras)", "value": "el dato tal como aparece (monto, fecha, plazo, etc.)", "explica": "una sola oración explicando qué significa ese dato, en lenguaje muy simple, como para alguien sin conocimientos legales" }
  ],
  "alerta": "una sola oración clara sobre el riesgo, penalización o cláusula más importante que la persona debe cuidar; si no encuentras ninguna cláusula riesgosa relevante, escribe una nota breve y tranquilizadora en su lugar",
  "esencial": ["3 a 5 puntos clave del contrato, cada uno una oración corta en español simple, sin tecnicismos"]
}

Incluye entre 3 y 5 elementos en "campos", priorizando montos de dinero, plazos/duración, y fechas importantes.
No uses tecnicismos legales. No agregues explicaciones fuera del JSON. No uses comillas triples ni la palabra json antes del objeto.`;

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result).split(",")[1]);
    reader.onerror = () => reject(new Error("No se pudo leer el archivo."));
    reader.readAsDataURL(file);
  });
}

async function fetchWithRetry(body, attempts = 3) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!response.ok) throw new Error("No pudimos conectar con el analizador.");
      return response;
    } catch (err) {
      lastErr = err;
      if (i < attempts - 1) {
        await new Promise((r) => setTimeout(r, 1000 * (i + 1)));
      }
    }
  }
  throw lastErr;
}

async function analyzeContract({ file, useSample }) {
  const contentBlocks = [];

  if (useSample || !file) {
    contentBlocks.push({ type: "text", text: "Documento a analizar:\n\n" + SAMPLE_CONTRACT_TEXT });
  } else if (file.type === "application/pdf") {
    const base64 = await fileToBase64(file);
    contentBlocks.push({ type: "document", source: { type: "base64", media_type: "application/pdf", data: base64 } });
  } else if (file.type && file.type.startsWith("image/")) {
    const base64 = await fileToBase64(file);
    contentBlocks.push({ type: "image", source: { type: "base64", media_type: file.type, data: base64 } });
  } else {
    throw new Error("Ese tipo de archivo no lo podemos leer.");
  }

  contentBlocks.push({ type: "text", text: ANALYSIS_INSTRUCTIONS });

  const response = await fetchWithRetry({
    model: "claude-sonnet-4-6",
    max_tokens: 1000,
    messages: [{ role: "user", content: contentBlocks }],
  });

  const data = await response.json();
  const textBlock = (data.content || []).find((b) => b.type === "text");
  if (!textBlock || !textBlock.text) {
    throw new Error("El analizador no devolvió una respuesta.");
  }

  const cleaned = textBlock.text.replace(/```json|```/g, "").trim();
  let parsed;
  try {
    parsed = JSON.parse(cleaned);
  } catch (e) {
    throw new Error("No entendimos el resultado del análisis.");
  }

  if (!parsed.tipo || !Array.isArray(parsed.campos) || !Array.isArray(parsed.esencial)) {
    throw new Error("El resultado no tiene el formato esperado.");
  }
  return parsed;
}

function PrivacyBadge({ onOpen, compact }) {
  if (compact) {
    return (
      <button
        onClick={onOpen}
        aria-label="Ver política de privacidad"
        style={{ background: TOKENS.paperDark, border: "none", borderRadius: 10, width: 40, height: 40, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 }}
      >
        <Lock size={18} color={TOKENS.ink} />
      </button>
    );
  }
  return (
    <button
      onClick={onOpen}
      style={{
        display: "flex", alignItems: "center", gap: 7, margin: "0 auto", background: "#EAF0FA", border: `1px solid ${TOKENS.inkSoft}`, borderRadius: 999, padding: "7px 14px", cursor: "pointer",
      }}
    >
      <Lock size={14} color={TOKENS.inkSoft} />
      <span style={{ fontFamily: "Inter, sans-serif", fontSize: 12.5, fontWeight: 600, color: TOKENS.inkSoft }}>
        Tus documentos están protegidos
      </span>
    </button>
  );
}

function PrivacyModal({ onClose, largeText }) {
  const base = largeText ? 17 : 15;
  const h = largeText ? 21 : 19;
  const points = [
    "Tu documento se usa solo para generar tu resumen, en el momento.",
    "No guardamos una copia de tu contrato después del análisis.",
    "No compartimos tu información con nadie, ni la vendemos.",
    "El envío de tu documento va cifrado, como en la banca en línea.",
  ];
  return (
    <div
      role="dialog"
      aria-modal="true"
      style={{ position: "absolute", inset: 0, background: "rgba(22,50,107,0.55)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20, zIndex: 20 }}
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{ background: "#FFFFFF", borderRadius: 22, padding: "26px 22px 22px", maxWidth: 340, width: "100%", boxShadow: "0 20px 40px rgba(0,0,0,0.3)" }}
      >
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}>
          <div style={{ width: 52, height: 52, borderRadius: 14, background: "#EAF0FA", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <ShieldCheck size={28} color={TOKENS.inkSoft} />
          </div>
          <button onClick={onClose} aria-label="Cerrar" style={{ background: "none", border: "none", cursor: "pointer", padding: 6 }}>
            <X size={22} color={TOKENS.textMuted} />
          </button>
        </div>
        <div style={{ fontFamily: "'Source Serif 4', serif", fontWeight: 700, fontSize: h, color: TOKENS.ink, margin: "10px 0 14px" }}>
          Tu privacidad es lo primero
        </div>
        <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 12 }}>
          {points.map((p, i) => (
            <li key={i} style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
              <CheckCircle2 size={18} color={TOKENS.forest} style={{ flexShrink: 0, marginTop: 2 }} />
              <span style={{ fontFamily: "Inter, sans-serif", fontSize: base, color: TOKENS.text, lineHeight: 1.5 }}>{p}</span>
            </li>
          ))}
        </ul>
        <button
          onClick={onClose}
          style={{ width: "100%", marginTop: 22, background: TOKENS.ink, color: "#FFF", border: "none", borderRadius: 14, padding: "14px", fontSize: base, fontWeight: 600, fontFamily: "Inter, sans-serif", cursor: "pointer" }}
        >
          Entendido
        </button>
      </div>
    </div>
  );
}

function StepIndicator({ currentIndex }) {
  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, padding: "12px 20px 4px" }}>
      {STEPS.map((s, i) => (
        <React.Fragment key={s}>
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
            <div style={{ width: 10, height: 10, borderRadius: "50%", background: i <= currentIndex ? TOKENS.ink : TOKENS.paperDark, transition: "background 0.3s" }} />
            <div style={{ fontSize: 10.5, fontFamily: "Inter, sans-serif", fontWeight: i === currentIndex ? 700 : 500, color: i <= currentIndex ? TOKENS.ink : TOKENS.textMuted }}>
              {s}
            </div>
          </div>
          {i < STEPS.length - 1 && (
            <div style={{ width: 22, height: 2, background: i < currentIndex ? TOKENS.ink : TOKENS.paperDark, marginBottom: 14 }} />
          )}
        </React.Fragment>
      ))}
    </div>
  );
}

function Seal({ show }) {
  return (
    <div style={{ width: 92, height: 92, borderRadius: "50%", border: `4px solid ${TOKENS.forest}`, display: "flex", alignItems: "center", justifyContent: "center", background: "#EAF0FA", transform: show ? "scale(1) rotate(-8deg)" : "scale(0) rotate(-40deg)", opacity: show ? 1 : 0, transition: "all 0.5s cubic-bezier(.34,1.56,.64,1)", boxShadow: show ? "0 4px 14px rgba(44,90,168,0.25)" : "none", flexShrink: 0 }}>
      <CheckCircle2 size={44} color={TOKENS.forest} strokeWidth={2.4} />
    </div>
  );
}

function BigButton({ icon: Icon, label, sub, onClick, tone = "ink" }) {
  const bg = tone === "ink" ? TOKENS.ink : "#FFFFFF";
  const color = tone === "ink" ? "#FFF" : TOKENS.ink;
  const border = tone === "ink" ? "none" : `2px solid ${TOKENS.ink}`;
  return (
    <button onClick={onClick} style={{ width: "100%", background: bg, color, border, borderRadius: 16, padding: "15px 18px", display: "flex", alignItems: "center", gap: 14, cursor: "pointer", fontFamily: "Inter, sans-serif", textAlign: "left", minHeight: 60 }}>
      <div style={{ background: tone === "ink" ? "rgba(255,255,255,0.15)" : TOKENS.paperDark, borderRadius: 11, width: 42, height: 42, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
        <Icon size={22} color={tone === "ink" ? "#FFF" : TOKENS.ink} />
      </div>
      <div>
        <div style={{ fontSize: 17, fontWeight: 600 }}>{label}</div>
        {sub && <div style={{ fontSize: 13.5, opacity: 0.75, marginTop: 2 }}>{sub}</div>}
      </div>
    </button>
  );
}

function TextToggle({ largeText, setLargeText }) {
  return (
    <button onClick={() => setLargeText((v) => !v)} aria-label="Cambiar tamaño de texto" style={{ background: largeText ? TOKENS.ink : TOKENS.paperDark, border: "none", borderRadius: 10, width: 40, height: 40, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 }}>
      <Type size={20} color={largeText ? "#FFF" : TOKENS.ink} />
    </button>
  );
}

function TopBar({ title, onBack, largeText, setLargeText, showTextToggle, onOpenPrivacy }) {
  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 18px", borderBottom: `1px solid ${TOKENS.paperDark}` }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10, minWidth: 40 }}>
        {onBack && (
          <button onClick={onBack} aria-label="Volver" style={{ background: "none", border: "none", cursor: "pointer", padding: 6, display: "flex" }}>
            <ArrowLeft size={24} color={TOKENS.ink} />
          </button>
        )}
      </div>
      <div style={{ fontFamily: "'Source Serif 4', serif", fontWeight: 600, fontSize: 19, color: TOKENS.ink }}>{title}</div>
      <div style={{ minWidth: 40, display: "flex", justifyContent: "flex-end", gap: 8 }}>
        <PrivacyBadge onOpen={onOpenPrivacy} compact />
        {showTextToggle && <TextToggle largeText={largeText} setLargeText={setLargeText} />}
      </div>
    </div>
  );
}

function HomeScreen({ onStartContract, onStartVigencia, onStartTramites, largeText, setLargeText, onOpenPrivacy }) {
  const [isSpeaking, setIsSpeaking] = useState(false);
  useEffect(() => stopSpeaking, []);

  const toggleListen = () => {
    if (isSpeaking) {
      stopSpeaking();
      setIsSpeaking(false);
      return;
    }
    speak(HOME_EXPLANATION, { onStart: () => setIsSpeaking(true), onEnd: () => setIsSpeaking(false) });
  };

  return (
    <div style={{ padding: "20px 22px 22px" }}>
      <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 6 }}>
        <TextToggle largeText={largeText} setLargeText={setLargeText} />
      </div>
      <div style={{ display: "flex", justifyContent: "center", marginBottom: 18 }}>
        <div style={{ width: 74, height: 74, borderRadius: 20, background: TOKENS.ink, display: "flex", alignItems: "center", justifyContent: "center" }}>
          <ShieldCheck size={34} color="#FFFFFF" />
        </div>
      </div>
      <h1 style={{ fontFamily: "'Source Serif 4', serif", fontSize: largeText ? 34 : 30, textAlign: "center", color: TOKENS.ink, margin: "0 0 8px", fontWeight: 700 }}>Kalan</h1>
      <p style={{ textAlign: "center", color: TOKENS.textMuted, fontSize: largeText ? 18 : 16, lineHeight: 1.5, margin: "0 0 28px", fontFamily: "Inter, sans-serif" }}>
        Sube cualquier contrato o documento y te explicamos, en palabras sencillas, qué dice y qué debes cuidar.
      </p>
      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
        <BigButton icon={Upload} label="Subir un documento" sub="PDF de tu contrato" onClick={onStartContract} />
        <BigButton icon={Camera} label="Tomar una foto" sub="Si tienes el papel en tus manos" onClick={onStartContract} tone="outline" />
      </div>

      <div style={{ display: "flex", gap: 10, marginTop: 18 }}>
        <button
          onClick={onStartVigencia}
          style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 6, background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 14, padding: "14px 8px", cursor: "pointer" }}
        >
          <CalendarCheck size={20} color={TOKENS.inkSoft} />
          <span style={{ fontFamily: "Inter, sans-serif", fontSize: 12.5, fontWeight: 600, color: TOKENS.inkSoft, textAlign: "center", lineHeight: 1.3 }}>
            Verificar vigencia
          </span>
        </button>
        <button
          onClick={onStartTramites}
          style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 6, background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 14, padding: "14px 8px", cursor: "pointer" }}
        >
          <ListChecks size={20} color={TOKENS.inkSoft} />
          <span style={{ fontFamily: "Inter, sans-serif", fontSize: 12.5, fontWeight: 600, color: TOKENS.inkSoft, textAlign: "center", lineHeight: 1.3 }}>
            Trámites en línea <span style={{ opacity: 0.6, fontWeight: 500 }}>(beta)</span>
          </span>
        </button>
      </div>
      <div style={{ marginTop: 16 }}>
        <PrivacyBadge onOpen={onOpenPrivacy} />
      </div>
      <button onClick={toggleListen} style={{ width: "100%", marginTop: 16, background: "none", border: "none", color: TOKENS.inkSoft, fontFamily: "Inter, sans-serif", fontSize: largeText ? 15.5 : 14, textDecoration: "underline", cursor: "pointer", padding: 8, display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }}>
        {isSpeaking ? <Square size={14} /> : <Volume2 size={16} />} {isSpeaking ? "Detener" : "Escuchar cómo funciona"}
      </button>
      <div style={{ marginTop: 14, background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 14, padding: "14px 16px", fontSize: largeText ? 15 : 13.5, color: TOKENS.textMuted, lineHeight: 1.5, fontFamily: "Inter, sans-serif" }}>
        Esto te ayuda a entender tus documentos, pero no sustituye el consejo de un profesional.
      </div>
    </div>
  );
}

function UploadScreen({ onSelectReal, onSelectSample, onSimulateBlurry, largeText, mode }) {
  const fileRef = useRef(null);
  const [inlineError, setInlineError] = useState("");

  const handlePick = (e) => {
    setInlineError("");
    const file = e && e.target && e.target.files && e.target.files[0];
    if (file) {
      const okType = file.type === "application/pdf" || file.type.startsWith("image/");
      if (!okType) {
        setInlineError("Ese tipo de archivo no lo podemos leer. Usa un PDF o una foto.");
        return;
      }
      onSelectReal(file);
    }
  };

  const base = largeText ? 18.5 : 17;
  const sub = largeText ? 16 : 14;

  return (
    <div style={{ padding: "12px 22px 18px" }}>
      <div onClick={() => fileRef.current && fileRef.current.click()} style={{ border: `2px dashed ${TOKENS.ink}`, borderRadius: 18, padding: "34px 20px", textAlign: "center", cursor: "pointer", background: "#FFFFFF" }}>
        <FileText size={36} color={TOKENS.ink} style={{ margin: "0 auto 12px" }} />
        <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: base, color: TOKENS.ink, marginBottom: 6 }}>Toca para elegir tu documento</div>
        <div style={{ fontSize: sub, color: TOKENS.textMuted, fontFamily: "Inter, sans-serif" }}>PDF o foto — nosotros nos encargamos del resto</div>
        <input ref={fileRef} type="file" accept="application/pdf,image/*" style={{ display: "none" }} onChange={handlePick} />
      </div>

      {inlineError && (
        <div style={{ marginTop: 12, background: "#FBEAE8", border: `1px solid ${TOKENS.brick}`, borderRadius: 12, padding: "10px 14px", display: "flex", gap: 8, alignItems: "center" }}>
          <AlertTriangle size={18} color={TOKENS.brick} style={{ flexShrink: 0 }} />
          <div style={{ fontSize: sub, color: TOKENS.brick, fontFamily: "Inter, sans-serif" }}>{inlineError}</div>
        </div>
      )}

      <div style={{ marginTop: 12, fontSize: sub - 1, color: TOKENS.textMuted, fontFamily: "Inter, sans-serif", textAlign: "center", lineHeight: 1.5 }}>
        Tu documento se analiza de forma segura y no se comparte con nadie más.
      </div>

      <button onClick={onSelectSample} style={{ marginTop: 16, width: "100%", background: TOKENS.ink, color: "#FFF", border: "none", borderRadius: 16, padding: "16px", fontSize: base, fontWeight: 600, fontFamily: "Inter, sans-serif", cursor: "pointer" }}>
        {mode === "vigencia" ? "Usar identificación de ejemplo" : "Usar contrato de ejemplo"}
      </button>

      <button onClick={onSimulateBlurry} style={{ marginTop: 10, width: "100%", background: "none", color: TOKENS.textMuted, border: `1.5px dashed ${TOKENS.paperDark}`, borderRadius: 16, padding: "12px", fontSize: sub, fontWeight: 500, fontFamily: "Inter, sans-serif", cursor: "pointer" }}>
        Probar caso: foto borrosa (demo)
      </button>
    </div>
  );
}

function ConfirmScreen({ fileName, onConfirm, onChangeFile, largeText, mode }) {
  const base = largeText ? 19 : 17;
  const sub = largeText ? 16 : 14;
  const [showHelp, setShowHelp] = useState(false);
  const isVigencia = mode === "vigencia";

  return (
    <div style={{ padding: "12px 22px 18px" }}>
      <div style={{ background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 18, padding: "22px 18px", textAlign: "center" }}>
        <div style={{ width: 64, height: 64, borderRadius: 16, background: TOKENS.paperDark, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 14px" }}>
          <FileText size={30} color={TOKENS.ink} />
        </div>
        <div style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: sub, color: TOKENS.textMuted, marginBottom: 10, wordBreak: "break-word" }}>{fileName}</div>
        <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: base, color: TOKENS.ink }}>
          {isVigencia ? "¿Es esta tu identificación?" : "¿Es este tu contrato?"}
        </div>
      </div>

      <button
        onClick={() => setShowHelp((v) => !v)}
        style={{ width: "100%", marginTop: 14, background: "none", border: "none", color: TOKENS.inkSoft, fontFamily: "Inter, sans-serif", fontSize: sub, textDecoration: "underline", cursor: "pointer", padding: 6, display: "flex", alignItems: "center", justifyContent: "center", gap: 6 }}
      >
        <HelpCircle size={18} /> {showHelp ? "Ocultar ejemplo" : "No entiendo esta pregunta, ver ejemplo"}
      </button>

      {showHelp && (
        <div style={{ marginTop: 8, background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 16, padding: "16px", display: "flex", flexDirection: "column", gap: 14 }}>
          <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.textMuted, lineHeight: 1.5, textAlign: "center" }}>
            Solo queremos asegurarnos de que subiste el papel correcto. Mira este ejemplo:
          </div>
          <div style={{ display: "flex", gap: 12 }}>
            <div style={{ flex: 1, border: `1.5px solid ${TOKENS.forest}`, borderRadius: 14, padding: "14px 10px", textAlign: "center", background: "#EAF0FA" }}>
              <FileText size={28} color={TOKENS.forest} style={{ margin: "0 auto 8px" }} />
              <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: sub - 1, color: TOKENS.forest, marginBottom: 4 }}>
                {isVigencia ? "Sí es una identificación" : "Sí es un contrato"}
              </div>
              <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub - 2, color: TOKENS.text, lineHeight: 1.4 }}>
                {isVigencia ? "Tiene tu foto, tu nombre y una fecha de vigencia." : "Tiene tu nombre, firmas y varias hojas con condiciones."}
              </div>
            </div>
            <div style={{ flex: 1, border: `1.5px solid ${TOKENS.brick}`, borderRadius: 14, padding: "14px 10px", textAlign: "center", background: "#FBEAE8" }}>
              <Receipt size={28} color={TOKENS.brick} style={{ margin: "0 auto 8px" }} />
              <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: sub - 1, color: TOKENS.brick, marginBottom: 4 }}>
                {isVigencia ? "No es una identificación" : "No es un contrato"}
              </div>
              <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub - 2, color: TOKENS.text, lineHeight: 1.4 }}>
                {isVigencia ? "Una tarjeta de puntos o una credencial de club no sirve." : "Un recibo, ticket o folleto no tiene firmas ni condiciones."}
              </div>
            </div>
          </div>
          <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub - 1, color: TOKENS.textMuted, lineHeight: 1.5, textAlign: "center" }}>
            Si tu papel se parece al de la izquierda, toca "Sí, continuar". Si no, toca "Elegir otro archivo".
          </div>
        </div>
      )}

      <div style={{ display: "flex", flexDirection: "column", gap: 12, marginTop: 20 }}>
        <button onClick={onConfirm} style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: TOKENS.ink, color: "#FFF", border: "none", borderRadius: 16, padding: "16px", fontSize: base, fontWeight: 600, fontFamily: "Inter, sans-serif", cursor: "pointer" }}>
          <Check size={22} /> Sí, continuar
        </button>
        <button onClick={onChangeFile} style={{ width: "100%", background: "#FFFFFF", color: TOKENS.ink, border: `2px solid ${TOKENS.ink}`, borderRadius: 16, padding: "14px", fontSize: sub, fontWeight: 600, fontFamily: "Inter, sans-serif", cursor: "pointer" }}>
          Elegir otro archivo
        </button>
      </div>
    </div>
  );
}

function ProcessingScreen({ mode }) {
  const steps =
    mode === "vigencia"
      ? ["Leyendo el documento…", "Buscando la fecha de vigencia…", "Preparando tu resultado…"]
      : ["Leyendo el documento…", "Detectando el tipo de contrato…", "Preparando tu resumen…"];
  const [step, setStep] = useState(0);
  useEffect(() => {
    const t = setInterval(() => setStep((s) => Math.min(s + 1, steps.length - 1)), 1100);
    return () => clearInterval(t);
  }, []);
  return (
    <div style={{ padding: "60px 30px", display: "flex", flexDirection: "column", alignItems: "center", gap: 24 }}>
      <div style={{ width: 64, height: 64, borderRadius: "50%", border: `5px solid ${TOKENS.paperDark}`, borderTopColor: TOKENS.ink, animation: "spin 1s linear infinite" }} />
      <div style={{ fontFamily: "Inter, sans-serif", fontSize: 17, fontWeight: 600, color: TOKENS.ink, textAlign: "center" }}>{steps[step]}</div>
      <div style={{ fontSize: 14, color: TOKENS.textMuted, textAlign: "center", fontFamily: "Inter, sans-serif" }}>Esto toma unos segundos, no cierres la aplicación.</div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}

function ErrorScreen({ onRetry, largeText, reason }) {
  const base = largeText ? 19 : 17;
  const sub = largeText ? 16.5 : 14.5;
  const isApiError = reason === "api";

  return (
    <div style={{ padding: "26px 22px 22px" }}>
      <div style={{ display: "flex", justifyContent: "center", marginBottom: 18 }}>
        <div style={{ width: 72, height: 72, borderRadius: "50%", background: "#FBEAE8", display: "flex", alignItems: "center", justifyContent: "center" }}>
          {isApiError ? <Wifi size={36} color={TOKENS.brick} /> : <AlertOctagon size={36} color={TOKENS.brick} />}
        </div>
      </div>
      <div style={{ fontFamily: "'Source Serif 4', serif", fontWeight: 700, fontSize: base + 3, color: TOKENS.ink, textAlign: "center", marginBottom: 10 }}>
        {isApiError ? "No pudimos analizar el documento" : "No pudimos leer este documento"}
      </div>
      <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.textMuted, textAlign: "center", lineHeight: 1.55, marginBottom: 22 }}>
        {isApiError
          ? "Hubo un problema al conectar con el analizador. Puede ser la conexión a internet."
          : "La foto salió borrosa o con poca luz. Esto puede ayudar:"}
      </div>

      <div style={{ background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 16, padding: "16px 18px", marginBottom: 24 }}>
        <ul style={{ margin: 0, paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
          {(isApiError
            ? ["Revisa que tengas conexión a internet.", "Espera unos segundos y vuelve a intentar.", "Si el problema sigue, pide ayuda a un familiar."]
            : ["Toma la foto con buena luz, de día si es posible.", "Pon el papel sobre una mesa, bien plano.", "Asegúrate de que se vean las 4 esquinas de la hoja."]
          ).map((tip, i) => (
            <li key={i} style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.text, lineHeight: 1.5 }}>{tip}</li>
          ))}
        </ul>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        <button onClick={onRetry} style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: TOKENS.ink, color: "#FFF", border: "none", borderRadius: 16, padding: "16px", fontSize: base, fontWeight: 600, fontFamily: "Inter, sans-serif", cursor: "pointer" }}>
          <RotateCcw size={20} /> Intentar de nuevo
        </button>
        <button style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "#FFFFFF", color: TOKENS.ink, border: `2px solid ${TOKENS.ink}`, borderRadius: 16, padding: "14px", fontSize: sub, fontWeight: 600, fontFamily: "Inter, sans-serif", cursor: "pointer" }}>
          <PhoneCall size={18} /> Pedir ayuda a un familiar
        </button>
      </div>
    </div>
  );
}

function Card({ children }) {
  return (
    <div style={{ background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 16, padding: "16px 18px", marginBottom: 14 }}>
      {children}
    </div>
  );
}

function TermRow({ label, value, explain, label_size, base_size, last }) {
  const [open, setOpen] = useState(false);
  return (
    <div style={{ marginBottom: last ? 0 : 10 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 }}>
        <button
          onClick={() => setOpen((v) => !v)}
          aria-label={"¿Qué significa " + label + "?"}
          style={{ display: "flex", alignItems: "center", gap: 5, background: "none", border: "none", cursor: "pointer", padding: 0, flexShrink: 0 }}
        >
          <span style={{ fontFamily: "Inter, sans-serif", fontSize: label_size, color: TOKENS.textMuted }}>{label}</span>
          <HelpCircle size={14} color={TOKENS.textMuted} />
        </button>
        <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: base_size, color: TOKENS.ink, fontWeight: 600, textAlign: "right" }}>{value}</span>
      </div>
      {open && (
        <div style={{ marginTop: 6, background: TOKENS.paperDark, borderRadius: 10, padding: "8px 12px", fontFamily: "Inter, sans-serif", fontSize: label_size, color: TOKENS.text, lineHeight: 1.5 }}>
          {explain}
        </div>
      )}
    </div>
  );
}

function SummaryScreen({ largeText, onReset, result }) {
  const [sealShown, setSealShown] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setSealShown(true), 150);
    return () => clearTimeout(t);
  }, []);
  useEffect(() => stopSpeaking, []);

  const base = largeText ? 20 : 16.5;
  const label = largeText ? 15.5 : 13.5;
  const h = largeText ? 24 : 20;

  const confianzaTexto = { alta: "Detectado con alta confianza", media: "Detectado con confianza media", baja: "No estamos del todo seguros" }[result.confianza] || "Análisis completado";

  const toggleListen = () => {
    if (isSpeaking) {
      stopSpeaking();
      setIsSpeaking(false);
      return;
    }
    speak(buildSpokenSummary(result, confianzaTexto), { onStart: () => setIsSpeaking(true), onEnd: () => setIsSpeaking(false) });
  };

  return (
    <div style={{ padding: "10px 20px 30px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 20 }}>
        <Seal show={sealShown} />
        <div>
          <div style={{ fontFamily: "Inter, sans-serif", fontSize: label, color: TOKENS.forest, fontWeight: 600, textTransform: "uppercase", letterSpacing: 0.4 }}>{confianzaTexto}</div>
          <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: h, color: TOKENS.ink, fontWeight: 700 }}>{result.tipo}</div>
        </div>
      </div>

      <Card>
        {result.campos.map((c, i) => (
          <TermRow key={i} label={c.label} value={c.value} explain={c.explica} label_size={label} base_size={base} last={i === result.campos.length - 1} />
        ))}
      </Card>

      <Card>
        <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
          <AlertTriangle size={22} color={TOKENS.brick} style={{ flexShrink: 0, marginTop: 2 }} />
          <div>
            <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: label, color: TOKENS.brick, marginBottom: 4 }}>Ojo con esto</div>
            <div style={{ fontFamily: "Inter, sans-serif", fontSize: base, color: TOKENS.text, lineHeight: 1.5 }}>{result.alerta}</div>
          </div>
        </div>
      </Card>

      <Card>
        <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: label, color: TOKENS.ink, marginBottom: 10 }}>Lo esencial</div>
        <ul style={{ margin: 0, paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
          {result.esencial.map((item, i) => (
            <li key={i} style={{ fontFamily: "Inter, sans-serif", fontSize: base, color: TOKENS.text, lineHeight: 1.5 }}>{item}</li>
          ))}
        </ul>
      </Card>

      <div style={{ display: "flex", gap: 12, marginTop: 8 }}>
        <button onClick={toggleListen} style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: isSpeaking ? TOKENS.paperDark : "#FFFFFF", border: `2px solid ${TOKENS.ink}`, borderRadius: 14, padding: "14px 10px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: 15, color: TOKENS.ink, cursor: "pointer" }}>
          {isSpeaking ? <Square size={18} /> : <Volume2 size={20} />} {isSpeaking ? "Detener" : "Escuchar"}
        </button>
        <button style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: TOKENS.ink, border: "none", borderRadius: 14, padding: "14px 10px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: 15, color: "#FFF", cursor: "pointer" }}>
          <Share2 size={20} /> Compartir
        </button>
      </div>

      <button onClick={onReset} style={{ width: "100%", marginTop: 14, background: "none", border: "none", color: TOKENS.textMuted, fontFamily: "Inter, sans-serif", fontSize: 14, textDecoration: "underline", cursor: "pointer", padding: 8 }}>
        Analizar otro contrato
      </button>
    </div>
  );
}

const ESTADO_STYLE = {
  vigente: { color: "#2C7A45", bg: "#E9F6EE", icon: CheckCircle2, label: "Vigente" },
  por_vencer: { color: "#B8790E", bg: "#FBF1E1", icon: Clock, label: "Por vencer" },
  vencido: { color: "#B23A2E", bg: "#FBEAE8", icon: CalendarX, label: "Vencido" },
  sin_fecha: { color: "#5B6474", bg: "#EEF0F3", icon: Info, label: "Sin fecha de vencimiento" },
};

function VigenciaSummaryScreen({ largeText, onReset, result }) {
  const [isSpeaking, setIsSpeaking] = useState(false);
  useEffect(() => stopSpeaking, []);

  const base = largeText ? 20 : 16.5;
  const label = largeText ? 15.5 : 13.5;
  const h = largeText ? 24 : 20;

  const style = ESTADO_STYLE[result.estado] || ESTADO_STYLE.sin_fecha;
  const StatusIcon = style.icon;
  const link = findOfficialLink(result.documento);

  const diasTexto =
    result.estado === "vencido" && result.dias != null
      ? `Venció hace ${result.dias} día${result.dias === 1 ? "" : "s"}`
      : (result.estado === "vigente" || result.estado === "por_vencer") && result.dias != null
      ? `Quedan ${result.dias} día${result.dias === 1 ? "" : "s"}`
      : null;

  const toggleListen = () => {
    if (isSpeaking) {
      stopSpeaking();
      setIsSpeaking(false);
      return;
    }
    speak(buildSpokenVigencia(result), { onStart: () => setIsSpeaking(true), onEnd: () => setIsSpeaking(false) });
  };

  return (
    <div style={{ padding: "10px 20px 30px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 20 }}>
        <div style={{ width: 76, height: 76, borderRadius: "50%", background: style.bg, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
          <StatusIcon size={36} color={style.color} />
        </div>
        <div>
          <div style={{ fontFamily: "Inter, sans-serif", fontSize: label, color: style.color, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.4 }}>{style.label}</div>
          <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: h, color: TOKENS.ink, fontWeight: 700 }}>{result.documento}</div>
        </div>
      </div>

      <Card>
        {result.fecha_vencimiento && (
          <div style={{ display: "flex", justifyContent: "space-between", marginBottom: diasTexto ? 8 : 0 }}>
            <span style={{ fontFamily: "Inter, sans-serif", fontSize: label, color: TOKENS.textMuted }}>Fecha de vencimiento</span>
            <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: base, color: TOKENS.ink, fontWeight: 600 }}>{result.fecha_vencimiento}</span>
          </div>
        )}
        {diasTexto && (
          <div style={{ display: "flex", justifyContent: "space-between" }}>
            <span style={{ fontFamily: "Inter, sans-serif", fontSize: label, color: TOKENS.textMuted }}>&nbsp;</span>
            <span style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: base, color: style.color, fontWeight: 700 }}>{diasTexto}</span>
          </div>
        )}
      </Card>

      <Card>
        <div style={{ fontFamily: "Inter, sans-serif", fontSize: base, color: TOKENS.text, lineHeight: 1.5 }}>{result.mensaje}</div>
      </Card>

      {result.recomendacion && (
        <Card>
          <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
            <Info size={20} color={TOKENS.inkSoft} style={{ flexShrink: 0, marginTop: 2 }} />
            <div style={{ fontFamily: "Inter, sans-serif", fontSize: base, color: TOKENS.text, lineHeight: 1.5 }}>{result.recomendacion}</div>
          </div>
          {link && (
            <a
              href={link.url}
              target="_blank"
              rel="noreferrer"
              style={{ marginTop: 12, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: TOKENS.ink, color: "#FFF", borderRadius: 12, padding: "12px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: label, textDecoration: "none" }}
            >
              <ExternalLink size={16} /> Ir al sitio oficial de {link.label}
            </a>
          )}
        </Card>
      )}

      <div style={{ display: "flex", gap: 12, marginTop: 8 }}>
        <button onClick={toggleListen} style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: isSpeaking ? TOKENS.paperDark : "#FFFFFF", border: `2px solid ${TOKENS.ink}`, borderRadius: 14, padding: "14px 10px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: 15, color: TOKENS.ink, cursor: "pointer" }}>
          {isSpeaking ? <Square size={18} /> : <Volume2 size={20} />} {isSpeaking ? "Detener" : "Escuchar"}
        </button>
        <button style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: TOKENS.ink, border: "none", borderRadius: 14, padding: "14px 10px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: 15, color: "#FFF", cursor: "pointer" }}>
          <Share2 size={20} /> Compartir
        </button>
      </div>

      <button onClick={onReset} style={{ width: "100%", marginTop: 14, background: "none", border: "none", color: TOKENS.textMuted, fontFamily: "Inter, sans-serif", fontSize: 14, textDecoration: "underline", cursor: "pointer", padding: 8 }}>
        Verificar otro documento
      </button>
    </div>
  );
}

function TramiteListScreen({ onSelect, largeText }) {
  const base = largeText ? 18 : 16.5;
  const sub = largeText ? 15 : 13.5;
  return (
    <div style={{ padding: "12px 22px 22px" }}>
      <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.textMuted, marginBottom: 16, lineHeight: 1.5, textAlign: "center" }}>
        Elige el trámite que quieres hacer. Te llevamos paso a paso.
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
        {TRAMITES.map((t) => (
          <button
            key={t.id}
            onClick={() => t.disponible && onSelect(t.id)}
            disabled={!t.disponible}
            style={{
              width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10,
              background: "#FFFFFF", border: `1.5px solid ${t.disponible ? TOKENS.ink : TOKENS.paperDark}`, borderRadius: 16,
              padding: "16px 18px", cursor: t.disponible ? "pointer" : "default", opacity: t.disponible ? 1 : 0.55, textAlign: "left",
            }}
          >
            <div>
              <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: base, color: TOKENS.ink }}>{t.titulo}</div>
              {!t.disponible && (
                <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub - 1, color: TOKENS.textMuted, marginTop: 2 }}>Próximamente</div>
              )}
            </div>
            {t.disponible && <ChevronRight size={20} color={TOKENS.ink} />}
          </button>
        ))}
      </div>
    </div>
  );
}

function TramiteGuideScreen({ tramite, largeText }) {
  const base = largeText ? 18.5 : 16.5;
  const sub = largeText ? 16 : 14;
  const h = largeText ? 22 : 19;
  const [done, setDone] = useState(() => tramite.pasos.map(() => false));
  const [openIndex, setOpenIndex] = useState(null);

  const toggleDone = (i) => setDone((d) => d.map((v, idx) => (idx === i ? !v : v)));
  const completedCount = done.filter(Boolean).length;

  return (
    <div style={{ padding: "12px 22px 26px" }}>
      <div style={{ fontFamily: "'Source Serif 4', serif", fontWeight: 700, fontSize: h, color: TOKENS.ink, marginBottom: 6 }}>{tramite.titulo}</div>
      <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.textMuted, lineHeight: 1.5, marginBottom: 14 }}>{tramite.descripcion}</div>

      <a
        href={tramite.sitioOficial}
        target="_blank"
        rel="noreferrer"
        style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: TOKENS.ink, color: "#FFF", borderRadius: 14, padding: "13px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: sub, textDecoration: "none", marginBottom: 16 }}
      >
        <ExternalLink size={16} /> Abrir sitio oficial
      </a>

      {tramite.documentos && tramite.documentos.length > 0 && (
        <Card>
          <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: sub, color: TOKENS.ink, marginBottom: 8 }}>Antes de empezar</div>
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            {tramite.documentos.map((d, i) => (
              <li key={i} style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.text, lineHeight: 1.5 }}>{d}</li>
            ))}
          </ul>
        </Card>
      )}

      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", margin: "18px 2px 10px" }}>
        <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 700, fontSize: sub, color: TOKENS.ink }}>Pasos a seguir</div>
        <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub - 1, color: TOKENS.textMuted }}>{completedCount} de {tramite.pasos.length}</div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {tramite.pasos.map((p, i) => (
          <div key={i} style={{ background: "#FFFFFF", border: `1px solid ${TOKENS.paperDark}`, borderRadius: 14, padding: "14px 16px", opacity: done[i] ? 0.6 : 1 }}>
            <div style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
              <button onClick={() => toggleDone(i)} aria-label={done[i] ? "Marcar como pendiente" : "Marcar como hecho"} style={{ background: "none", border: "none", cursor: "pointer", padding: 0, marginTop: 1, flexShrink: 0 }}>
                {done[i] ? <CheckCircle2 size={22} color={TOKENS.forest} /> : <Circle size={22} color={TOKENS.textMuted} />}
              </button>
              <div style={{ flex: 1 }}>
                <div
                  onClick={() => setOpenIndex(openIndex === i ? null : i)}
                  style={{ display: "flex", justifyContent: "space-between", alignItems: "center", cursor: "pointer" }}
                >
                  <div style={{ fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: base, color: TOKENS.ink, textDecoration: done[i] ? "line-through" : "none" }}>
                    {i + 1}. {p.titulo}
                  </div>
                  <ChevronRight size={18} color={TOKENS.textMuted} style={{ transform: openIndex === i ? "rotate(90deg)" : "none", transition: "transform 0.2s", flexShrink: 0 }} />
                </div>
                {openIndex === i && (
                  <div style={{ marginTop: 8, fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.text, lineHeight: 1.5 }}>{p.detalle}</div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      {completedCount === tramite.pasos.length && (
        <div style={{ marginTop: 16, background: "#E9F6EE", border: `1px solid ${TOKENS.forest}`, borderRadius: 14, padding: "14px 16px", display: "flex", gap: 10, alignItems: "center" }}>
          <CheckCircle2 size={22} color={TOKENS.forest} style={{ flexShrink: 0 }} />
          <div style={{ fontFamily: "Inter, sans-serif", fontSize: sub, color: TOKENS.text, lineHeight: 1.5 }}>¡Completaste todos los pasos! Ya deberías tener tu documento listo.</div>
        </div>
      )}

      <button style={{ width: "100%", marginTop: 16, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "#FFFFFF", border: `2px solid ${TOKENS.ink}`, borderRadius: 14, padding: "13px", fontFamily: "Inter, sans-serif", fontWeight: 600, fontSize: sub, color: TOKENS.ink, cursor: "pointer" }}>
        <Share2 size={18} /> Compartir esta guía
      </button>
    </div>
  );
}

export default function KalanApp() {
  const [screen, setScreen] = useState("home");
  const [mode, setMode] = useState("contract");
  const [largeText, setLargeText] = useState(false);
  const [fileName, setFileName] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [useSample, setUseSample] = useState(false);
  const [willFail, setWillFail] = useState(false);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [errorReason, setErrorReason] = useState("blurry");
  const [showPrivacy, setShowPrivacy] = useState(false);
  const [selectedTramiteId, setSelectedTramiteId] = useState(null);

  const onStartContract = () => {
    setMode("contract");
    setScreen("upload");
  };
  const onStartVigencia = () => {
    setMode("vigencia");
    setScreen("upload");
  };
  const onStartTramites = () => setScreen("tramites");
  const onSelectTramite = (id) => {
    setSelectedTramiteId(id);
    setScreen("tramiteGuide");
  };

  const onSelectReal = (file) => {
    setSelectedFile(file);
    setFileName(file.name);
    setUseSample(false);
    setWillFail(false);
    setScreen("confirm");
  };
  const onSelectSample = () => {
    setSelectedFile(null);
    setFileName(mode === "vigencia" ? "identificacion_ejemplo.jpg" : "contrato_ejemplo.pdf");
    setUseSample(true);
    setWillFail(false);
    setScreen("confirm");
  };
  const onSimulateBlurry = () => {
    setSelectedFile(null);
    setFileName("foto_borrosa.jpg");
    setUseSample(false);
    setWillFail(true);
    setScreen("confirm");
  };

  const startProcessing = async () => {
    setScreen("processing");
    if (willFail) {
      setTimeout(() => {
        setErrorReason("blurry");
        setScreen("error");
      }, 2200);
      return;
    }
    try {
      const result =
        mode === "vigencia"
          ? await analyzeVigencia({ file: selectedFile, useSample })
          : await analyzeContract({ file: selectedFile, useSample });
      setAnalysisResult(result);
      setScreen("summary");
    } catch (err) {
      console.error(err);
      setErrorReason("api");
      setScreen("error");
    }
  };

  const reset = () => {
    setScreen("home");
    setFileName("");
    setSelectedFile(null);
    setUseSample(false);
    setWillFail(false);
    setAnalysisResult(null);
  };
  const retryFromError = () => {
    setWillFail(false);
    setScreen("upload");
  };

  const titles = {
    home: "",
    upload: mode === "vigencia" ? "Verificar documento" : "Nuevo contrato",
    confirm: "Confirmar",
    processing: "Analizando",
    error: "Necesitamos tu ayuda",
    summary: mode === "vigencia" ? "Resultado" : "Tu resumen",
    tramites: "Trámites en línea",
    tramiteGuide: "Guía paso a paso",
  };

  const stepIndex = { upload: 0, confirm: 1, processing: 2, summary: 3 }[screen];

  const backHandlers = {
    upload: () => setScreen("home"),
    confirm: () => setScreen("upload"),
    error: () => setScreen("upload"),
    summary: reset,
    tramites: () => setScreen("home"),
    tramiteGuide: () => setScreen("tramites"),
  };

  return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "#D9DFEC", fontFamily: "Inter, sans-serif", padding: "24px 12px" }}>
      <style>{FONTS}</style>
      <div style={{ width: 390, maxWidth: "100%", minHeight: 720, background: TOKENS.paper, borderRadius: 34, border: `8px solid #16326B`, overflow: "hidden", boxShadow: "0 20px 50px rgba(0,0,0,0.25)", display: "flex", flexDirection: "column", position: "relative" }}>
        {screen !== "home" && (
          <TopBar
            title={titles[screen]}
            onBack={backHandlers[screen] || null}
            largeText={largeText}
            setLargeText={setLargeText}
            showTextToggle={screen !== "processing"}
            onOpenPrivacy={() => setShowPrivacy(true)}
          />
        )}
        {stepIndex !== undefined && <StepIndicator currentIndex={stepIndex} />}
        <div style={{ flex: 1, overflowY: "auto" }}>
          {screen === "home" && (
            <HomeScreen onStartContract={onStartContract} onStartVigencia={onStartVigencia} onStartTramites={onStartTramites} largeText={largeText} setLargeText={setLargeText} onOpenPrivacy={() => setShowPrivacy(true)} />
          )}
          {screen === "upload" && (
            <UploadScreen onSelectReal={onSelectReal} onSelectSample={onSelectSample} onSimulateBlurry={onSimulateBlurry} largeText={largeText} mode={mode} />
          )}
          {screen === "confirm" && (
            <ConfirmScreen fileName={fileName} onConfirm={startProcessing} onChangeFile={() => setScreen("upload")} largeText={largeText} mode={mode} />
          )}
          {screen === "processing" && <ProcessingScreen mode={mode} />}
          {screen === "error" && <ErrorScreen onRetry={retryFromError} largeText={largeText} reason={errorReason} />}
          {screen === "summary" && analysisResult && mode === "contract" && <SummaryScreen largeText={largeText} onReset={reset} result={analysisResult} />}
          {screen === "summary" && analysisResult && mode === "vigencia" && <VigenciaSummaryScreen largeText={largeText} onReset={reset} result={analysisResult} />}
          {screen === "tramites" && <TramiteListScreen onSelect={onSelectTramite} largeText={largeText} />}
          {screen === "tramiteGuide" && selectedTramiteId && (
            <TramiteGuideScreen tramite={TRAMITES.find((t) => t.id === selectedTramiteId)} largeText={largeText} />
          )}
        </div>
        {screen === "home" && (
          <div style={{ display: "flex", justifyContent: "center", padding: "10px 0 16px", color: TOKENS.textMuted }}>
            <HomeIcon size={18} />
          </div>
        )}
        {showPrivacy && <PrivacyModal onClose={() => setShowPrivacy(false)} largeText={largeText} />}
      </div>
    </div>
  );
}
